---
title: "Road_Suffix"
output: html_document
---

```{r}
library(tidyverse)
library(readxl)

library(RColorBrewer)
library(hrbrthemes)

library(extrafont)
hrbrthemes::import_roboto_condensed()
font_import()
```

```{r}
## Define Plot Theme
plot_theme <- function(...) {

  # theme_minimal() + #For knit as pdf
  theme_ipsum_rc() +
    theme(
      legend.position = "none",
      panel.spacing = unit(1, "lines"),
      strip.text.x = element_text(size = 8),
      plot.title.position = "plot"
    ) +
    theme(...)
}

plot_theme_dark <- function(...) {
  theme_ipsum_rc() +
    theme(
      legend.position = "none",
      panel.spacing = unit(1, "lines"),
      strip.text.x = element_text(size = 8),
      plot.title.position = "plot",

      panel.background = element_rect(fill = "#333333", color = "#333333"), # Fill inside plot area
      plot.background = element_rect(fill = "#333333", color = "#333333"), # Fill outside plot area
      text = element_text(color = "#FFFFFF"),
      axis.text = element_text(color = "#FFFFFF")
    ) +
    theme(...)
}
```




Need to solve utf-8 problem using read excel, read_csv fails
Use read_excel if encoding fails

```{r}
# https://readxl.tidyverse.org/
RoadSuffix_Unique <- read_csv("data/data-output/RoadSuffix_Unique.csv")
```



```{r}
RoadSuffix_Unique$SUF_ENG_G <- as.factor(RoadSuffix_Unique$SUF_ENG_G)
RoadSuffix_Unique$SUF_CHI_G <- as.factor(RoadSuffix_Unique$SUF_CHI_G)

RoadSuffix_Unique$SUF_CHI_G <- fct_relevel(RoadSuffix_Unique$SUF_CHI_G, c("公路", "道", "路", "街", "徑", "里", "其他", "無名"))

RoadSuffix_Unique$SUF_ENG_G <- fct_relevel(RoadSuffix_Unique$SUF_ENG_G, c("HIGHWAY", "ROAD",  "DRIVE", "AVENUE", "STREET", "PATH", "LANE", "OTHERS", "NODATA"))


```




```{r}
# TODO: duplicate rows after complete, why?

Suffix_Unique_Plot <- RoadSuffix_Unique %>%
  group_by(SUF_ENG_G, SUF_CHI_G) %>%
  summarise(count = n()) %>%
  complete(SUF_ENG_G, SUF_CHI_G) %>%
  unique()
  
```

```{r, eval = FALSE}
#Work around to get every possible CHI/ENG pair
# https://stackoverflow.com/questions/45832096/group-by-and-summarise-with-all-combinations-including-non-existing-combina


Suffix_Unique_Plot <- RoadSuffix_Unique %>%
  group_by(SUF_ENG_G, SUF_CHI_G) %>%
  summarise(count = n()) %>%
  spread(SUF_ENG_G, count) %>%
  gather(SUF_ENG_G, count, -SUF_CHI_G)


# SUF_ENG_G turned to char again after spread
# DIRTY
Suffix_Unique_Plot$SUF_ENG_G <- as.factor(Suffix_Unique_Plot$SUF_ENG_G)

Suffix_Unique_Plot$SUF_ENG_G <- fct_relevel(Suffix_Unique_Plot$SUF_ENG_G, c("HIGHWAY", "ROAD",  "DRIVE", "AVENUE", "STREET", "PATH", "LANE", "OTHERS", "NODATA"))

```

## Reorder

```{r}
levels(Suffix_Unique_Plot$SUF_CHI_G)
levels(Suffix_Unique_Plot$SUF_ENG_G)
```



```{r}
## fct_rev to plot from top to bottom
## default y drawing reorder is from bottom to top

## https://stackoverflow.com/questions/52378434/change-color-of-text-based-on-threshold
## scale_color_identity() to tell ggplot2 use colors defined above directly, as aes values, otherwise text colour also affected

## Fill by logged count values to allow more even "spread" of distribution

ggplot(Suffix_Unique_Plot, aes(x = SUF_ENG_G, y = fct_rev(SUF_CHI_G), fill = log(count))) +
  geom_tile(color = "#EEEEEE", size = 1) +
  geom_text(aes(label = count, color = ifelse(count > 100, "#FFFFFF", "#222222"))) +
  #scale_fill_distiller(type = "seq", palette = "Greens", na.value = '#DDDDDD', direction = 1) +
  scale_fill_viridis_c(na.value = '#DDDDDD', direction = -1) +
  scale_color_identity() +
  scale_x_discrete(position = "top") +
  plot_theme_dark(
    panel.grid.major = element_blank(),
    axis.title.x = element_blank(),
    axis.title.y = element_blank()) +
  labs(
    title = "Chinese Street Suffix vs English Street Suffix"
  )
```

```{r}
ggplot(RoadSuffix_Unique, aes(y = fct_rev(SUF_CHI_G), fill = SUF_CHI_G)) +
  geom_bar() +
  geom_text(aes(label = ..count.., color = "#FFFFFF"), stat='count', hjust = 1.15) +
  scale_color_identity() +
  plot_theme_dark(
    axis.title.y = element_blank(),
    panel.grid.major.y = element_blank(), # exlucde y main axis
    aspect.ratio = 1/2
  ) +
  labs(
    title = "Suffix of Chinese Street Names"
  )

#ggsave("Suffix_Chi.pdf", device = "pdf", width = 200, unit = "mm")
```

```{r}
ggplot(RoadSuffix_Unique, aes(y = fct_rev(SUF_ENG_G), fill = SUF_ENG_G)) +
  geom_bar() +
  geom_text(aes(label = ..count.., color = "#FFFFFF"), stat='count', hjust = 1.15) +
  scale_color_identity() +
  plot_theme_dark(
    # plot.title = element_text(size = 22),
    panel.grid.major.y = element_blank(), # exlucde y main axis
    axis.title.y = element_blank(),
    aspect.ratio = (1/2)*(8/7)
  ) +
  labs(
    title = "Suffix of English Road Names"
  )
```
